# Setup
title:               A Developer's Journal
tagline:             "by VulcanSmithy"
description:         'A collection of notes related to the dark art of coding and programming.'
url:                 https://vulcansmithy.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vulcan Smithy
  url:               https://github.com/vulcansmithy
  email:             vulcansmithy.workshop@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

